// module.exports = {
//   validation_failed: 'validation failed',
//   shop_exists: 'shop already exists',
//   user_exists: 'user already exists',
//   invalid_shop: 'No shop was found.',
//   invalid_user: 'No user was found.',
//   invalid_password: 'invalid password',
//   password_not_match: 'Password does not match',
//   user_not_found: 'User not found',
//   phone_already_used: 'phone already in use',
//   email_already_used: 'Email already in use',
//   cpf_already_used: 'CPF already in use',
//   user_cannot_create_shop: 'A user cannot include a shop in the system',
//   feedback_already_stored: 'Feedback already registered to a user',
// };

module.exports = {
  validation_failed: 'Validação falhou',
  shop_exists: 'Loja já existe',
  user_exists: 'Usuário já existe',
  invalid_shop: 'Nenhuma loja foi encontrada.',
  invalid_user: 'Usuário inválido.',
  invalid_password: 'Senha inválida',
  password_not_match: 'Senha não confere',
  user_not_found: 'Usuário não encontrado',
  phone_already_used: 'Numero de telefone já em uso',
  email_already_used: 'Email já em uso',
  cpf_already_used: 'CPF já cadastrado',
  user_cannot_create_shop: 'Um consumidor não pode incluir uma loja',
  feedback_already_stored: 'Feedback já registrado por um usuário',
  ok: 'feito',
};
